FROM bitnami/dotnet-sdk:latest AS build

RUN mkdir -p /app
WORKDIR /app
COPY . ./
RUN dotnet restore
RUN dotnet publish -o /appOut

FROM bitnami/aspnet-core:latest AS runtime
WORKDIR /app
COPY --from=build ./appOut .
EXPOSE 5000
ENTRYPOINT [ "dotnet", "MySqlApi.dll" ]