name: Pull Request Checks

on:
  pull_request:
    branches:
      - main
      - staging

jobs:
  validar-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
  
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install -g @commitlint/config-conventional @commitlint/cli

      - name: Validar Commits
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

  validar-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Teste de Build
        run: dotnet build

      - name: Testes Unitarios
        run: dotnet test --no-build
